### ISSUE TITLE
Changing the credentials for mysql

### ISSUE THREAD

**Issue by lucqui** [dzinot/spring-boot-oauth2-jwt#1]
Hi, this looks like a great app.

I'm getting `java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES).` 

Where can I change this in your code? Where can I alter the values of the db.* properties in the application.yml? Thanks.

**Comment by dzinot** [comment]
Thanks.

You can change the DB configuration in the application.yaml (src/main/resources/application.yml).

```
spring:
  datasource:
    url: jdbc:mysql://${db.host:YOUR_HOST}:${db.port:YOUR_PORT}/${db.name:YOUR_DB_NAME}?useSSL=false
    username: ${db.uid:YOUR_DB_USER}
    password: ${db.pwd:YOUR_DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver
```
